version: '3.7'

volumes:
  plex-config: null

networks:
  default:
    driver: bridge

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    privileged: true
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - VERSION=docker
      # - PLEX_CLAIM=optional
    depends_on:
      - goofys
    volumes:
      - plex-config:/config
      - './data/minio_fs:/mnt/s3:shared'
    restart: unless-stopped
    networks:
      default:

  goofys:
    container_name: goofys
    image: ghcr.io/acidtib/goofys:latest
    privileged: true
    environment:
      - ENDPOINT=http://minio1:9001
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - BUCKET=plex-server
      - REGION=unused 
      - UID=1000
      - GID=1000
      - DIR_MODE=0777
      - FILE_MODE=0777
      - STAT_CACHE_TTL=0s
      - TYPE_CACHE_TTL=0s
      - MOUNT_ACCESS=allow_other,nonempty
    volumes:
      - './config/fuse.conf:/etc/fuse.conf'
      - './data/minio_fs:/mnt/s3:shared'
    networks:
      default: